const ASYNC_FETCH_FLIGHTS = "ASYNC_FETCH_FLIGHTS";
const FETCH_FLIGHTS = "FETCH_FLIGHTS";
const FETCH_FLIGHTS_SUCCESS = "FETCH_FLIGHTS_SUCCESS";
const FETCH_FLIGHTS_FAILED = "FETCH_FLIGHTS_FAILED";
const SET_CARRIERS = "SET_CARRIERS";
const ADD_FAVORITES = "ADD_FAVORITES"
const REMOVE_FAVORITES = "REMOVE_FAVORITES"
const FAVORITES_FLIGHTS = "FAVORITES_FLIGHTS"
export {ASYNC_FETCH_FLIGHTS, FETCH_FLIGHTS, FETCH_FLIGHTS_SUCCESS, FETCH_FLIGHTS_FAILED,
    ADD_FAVORITES, REMOVE_FAVORITES, SET_CARRIERS, FAVORITES_FLIGHTS};
